# Monotheme
[colors.primary]
  background = "0x161A19"
  foreground = "0xa0a0a0"

[colors.normal]
  black = "0x000000"
  red = "0x6b6b6b"
  green = "0xc4c4c4"
  yellow = "0xb3b3b3"
  blue = "0x999999"
  magenta = "0x717171"
  cyan = "0x8a8a8a"
  white = "0xb5cabb"

[colors.bright]
  black = "0x202020"
  red = "0x464646"
  green = "0xf8f8f8"
  yellow = "0xeeeeee"
  blue = "0x7c7c7c"
  magenta = "0xadadad"
  cyan = "0xc0c0c0"
  white = "0x99ac9e"

[font]
  size = 10

[font.normal]
  family = "Hack"

[window]
  opacity = 0.9

[window.padding]
  x = 20
  y = 10

[mouse]
  hide_when_typing = true
