[als.iio]
path = "/sys/bus/iio/devices"
thresholds = { 0 = "night", 20 = "dark", 80 = "dim", 250 = "normal", 500 = "bright", 800 = "outdoors" }

[[output.backlight]]
name = "eDP-1"
path = "/sys/class/backlight/intel_backlight"
capturer = "none"

[[keyboard]]
name = "keyboard-dell"
path = "/sys/bus/platform/devices/dell-laptop/leds/dell::kbd_backlight"
