backend = "glx";
xrender-sync-fence = true;
glx-no-stencil = true;
/* glx-swap-method = "6"; */ /* Causes flickering */
glx-copy-from-front = false;
/* fading = true; */
/* fade-delta = 2; */
/* inactive-opacity = 0.8; */
/* focus-exclude = [ */
/* 	"name = 'Notification'", */
/* 	"name *= 'i3lock'", */
/* 	"class_g = 'Dmenu'", */
/* 	"class_g = 'Firefox' && argb" */
/* ]; */
shadow = true;
no-dnd-shadow = true;
no-dock-shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-exclude = [
	"class_g = 'Conky'",
	"class_g ?= 'Notify-osd'",
	"class_g = 'Cairo-clock'", 
	"_GTK_FRAME_EXTENTS@:c",
	"class_g = 'Firefox' && argb"
];
detect-rounded-corners = true;
detect-transient = true;
detect-client-leader = true;
clear-shadow = true;
