vsync   = true;
backend = "glx";
xrender-sync-fence = true;
glx-no-stencil = true;
glx-copy-from-front = false;

/* shadow = true; */
shadow-radius = 7;
shadow-offset-x = -3;
shadow-offset-y = -3;
shadow-exclude = [
	"class_g = 'Conky'",
	"class_g ?= 'Notify-osd'",
	"class_g = 'Cairo-clock'", 
	"_GTK_FRAME_EXTENTS@:c",
	"class_g = 'Firefox' && argb"
];

detect-transient = true;
detect-client-leader = true;

wintypes:
{
	tooltip = { opacity = 0.95; shadow = false; fade = true; focus = true; };
	dock = { shadow = false; };
	dnd = { shadow = false; };
};

