#! /bin/bash

sxhkd &
polybar bottom &

bspc monitor -d 一 二 三 四 五 六 七 八 九

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config border_width			0
bspc config window_gap				10

bspc config presel_feedback_color	"#f46067"

bspc config split_ratio				0.5
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config border_radius			8

# Ignore focus steal
bspc config ignore_ewmh_focus true

bspc rule -a Firefox 			desktop='^2'
bspc rule -a TelegramDesktop	desktop='^5'
bspc rule -a Ferdi				desktop='^5'
bspc rule -a compenda-app		desktop='^0'

bspc config focus_follows_pointer 	true
