#! /bin/sh

sxhkd &
polybar bottom &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a Telegram desktop='^5'
bspc rule -a Franz    desktop='^5'

bspc config focus_follows_pointer true
